accounts/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [path("signup/", SignUpView.as_view(), name="signup")]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("quotes.urls")),
]

quotes/urls.py
from django.urls import path

from .views import (
    QuotesListView,
    AuthorDetailView,
    TagDetailView,
    QuoteCreateView,
    TagCreateView,
    AuthorCreateView,
)

app_name = "quotes"

urlpatterns = [
    path("tag/new/", TagCreateView.as_view(), name="tag_new"),
    path("author/new/", AuthorCreateView.as_view(), name="author_new"),
    path("quote/new/", QuoteCreateView.as_view(), name="quote_new"),
    path("author/<slug:slug>", AuthorDetailView.as_view(), name="author_detail"),
    path("tag/<slug:slug>", TagDetailView.as_view(), name="tag_detail"),
    path("", QuotesListView.as_view(), name="home"),
]

accounts/models.py
from django.db import models

# Create your models here.

quotes/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse


class Author(models.Model):
    fullname = models.CharField(max_length=255, null=False)
    born_date = models.DateField()
    born_location = models.CharField(max_length=255)
    biography = models.TextField()
    user = models.ForeignKey("auth.User", on_delete=models.DO_NOTHING, default=1)
    slug = models.SlugField(unique=True)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.fullname

    def get_absolute_url(self):
        return reverse("author_detail", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.fullname)
        return super().save(*args, **kwargs)


class Tag(models.Model):
    tag = models.CharField(max_length=128, null=False, unique=True)
    user = models.ForeignKey("auth.User", on_delete=models.DO_NOTHING, default=1)
    slug = models.SlugField(unique=True)
    created_at = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ("tag",)

    def __str__(self):
        return f"{self.tag}"

    def get_absolute_url(self):
        return reverse("tag_detail", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.tag)
        return super().save(*args, **kwargs)


class Quote(models.Model):
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=1)
    quote = models.TextField()
    user = models.ForeignKey("auth.User", on_delete=models.DO_NOTHING, default=1)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.quote[:56] + "..."

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'username',
            'email'
        )

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from accounts.forms import CustomUserCreationForm


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

quotes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView

from .models import Quote, Author, Tag


class QuotesListView(ListView):
    paginate_by = 7
    model = Quote
    template_name = "home.html"


class AuthorDetailView(DetailView):
    model = Author
    template_name = "author_detail.html"


class TagDetailView(DetailView):
    model = Tag
    template_name = "tag_detail.html"

    def get_context_data(self, **kwargs):
        context = super(TagDetailView, self).get_context_data(**kwargs)
        activities = self.get_related_activities()
        context['quote_list'] = activities
        context['page_obj'] = activities
        return context

    def get_related_activities(self):
        queryset = Quote.objects.filter(tags__tag__contains=self.object)
        paginator = Paginator(queryset, 4)  # paginate_by
        page = self.request.GET.get('page')
        activities = paginator.get_page(page)
        return activities


class QuoteCreateView(LoginRequiredMixin, CreateView):
    model = Quote
    template_name = "quote_new.html"
    fields = ["tags", "author", "quote"]
    success_url = "/"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TagCreateView(LoginRequiredMixin, CreateView):
    model = Tag
    template_name = "tag_new.html"
    fields = [
        "tag",
    ]
    success_url = "/quote/new/"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class AuthorCreateView(LoginRequiredMixin, CreateView):
    model = Author
    template_name = "author_new.html"
    fields = ["fullname", "born_date", "born_location", "biography"]
    success_url = "/quote/new/"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

templates/author_detail.html
{% extends 'base.html' %}

{% block content %}

    <div class="author_detail">
        <h3 class="author-title">{{ author.fullname }}</h3>
        <p>
            <strong>Born:</strong>
            <span class="author-born-date">{{ author.born_date }}</span>
            <span class="author-born-location">{{ author.born_location }}</span>
        </p>
        <p>
            <strong>Description:</strong>
        </p>
        <div class="author-biography">{{ author.biography }}</div>
    </div>



{% endblock content %}

templates/author_new.html
{% extends 'base.html' %}

{% block content %}

    <h1>New Author</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>

{% endblock content %}

templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Quotes</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    {#    <link  href="{% static 'css/base.css' %}" rel="stylesheet">#}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>

<header class="p-3 mb-3 border-bottom">
    <div class="container ">
        <nav class="navbar ">
            <div class="container-fluid">
                <h1>
                    <a class="navbar-brand fs-1 fw-bold" href="{% url 'quotes:home' %}">Quotes to
                        Scrape</a>
                </h1>
                <a class="d-flex" href="{% url 'quotes:quote_new' %}">+ New Quote</a>
            </div>
        </nav>
    </div>
</header>

<div class="container py-2">

    <div style="margin-bottom: 2rem">
        {% if user.is_authenticated %}
            <p>Hi, {{ user.username }}</p>
            <a href="{% url 'logout' %}">Log Out</a>
        {% else %}
            <p>You are not logged in.</p>
            <a href="{% url 'login' %}">Log In</a> |
            <a href="{% url 'signup' %}">Sign Up</a>
        {% endif %}
    </div>

    <div>
        {% block content %}
        {% endblock content %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
            crossorigin="anonymous"></script>
</div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load extract_tags %}

{% block content %}

    {% for quote in quote_list %}
        <div class="card" style="margin-bottom: 1px">
            <div class="card-body">
                <div style="margin-bottom: 10px">
                    <span class="fst-italic">{{ quote.quote }}</span>
                </div>
                <div>
                    <span> by
                <small class="fw-bold">{{ quote.author }}</small>
                 <a class="author-link" href="{% url 'quotes:author_detail' quote.author.slug %}">(about)</a>
                    </span>
                </div>

                <div>Tags:
                    {% for tag in quote.tags|tags %}
                        <a class="badge bg-primary text-wrap "
                           style="width: fit-content; text-decoration: none;"
                           href="{% url 'quotes:tag_detail' tag.slug %}">{{ tag }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endfor %}


    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
    </div>

{% endblock content %}

templates/quote_new.html
{% extends 'base.html' %}

{% block content %}

    <h1>New Quote</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
    <div>
        <a href="{% url 'quotes:tag_new' %}">+ New Tag</a>
    </div>
    <div>
        <a href="{% url 'quotes:author_new' %}">+ New Author</a>
    </div>

{% endblock content %}

templates/tag_detail.html
{% extends 'base.html' %}
{% load extract_tags %}

{% block content %}

    <h3>Viewing tag:
        <span>{{ tag.tag }}</span>
    </h3>

    {% for quote in quote_list %}

        <div class="card" style="margin-bottom: 1px">
            <div class="card-body">

                <div style="margin-bottom: 10px">
                    <span class="fst-italic">{{ quote.quote }}</span>
                </div>
                <div>
                         <span> by
                            <small class="fw-bold">{{ quote.author }}</small>
                            <a class="author-link" href="{% url 'quotes:author_detail' quote.author.slug %}">(about)</a>
                        </span>
                </div>

                <div>Tags:
                    {% for tag in quote.tags|tags %}
                        <a class="badge bg-primary text-wrap" style="width: fit-content; text-decoration: none"
                           href="{% url 'quotes:tag_detail' tag.slug %}">{{ tag }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>

    {% endfor %}

    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
    </div>

{% endblock content %}

templates/tag_new.html
{% extends 'base.html' %}

{% block content %}

    <h1>New Tag</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>

{% endblock content %}